First repo
avinetworks/alb-vmexplore pull request #1
Opened 2022-07-31 23:57 UTC by itlinux

I shared the original with Nick from my repo. Pushing the changes to here.

2022-08-02 17:53 UTC, grastogi23 requested changes

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +    - name: Get GSLB list
I would suggest add a Prefix to all the tasks so it shows in debug like

Avi Absent | Get GSLB list or 
Avi New Deployment | Get GSLB list

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +      ignore_errors: yes
why ignore errors is set to yes?

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +    - name: get VS
Get All Virtual Services to build a List for Deletion
Also, this is not going to work when there are 100s of VS. You also need pagination. Not, sure what you are doing here.

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +    - name: Delete child VS config
there is no filtering happening here.

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +    - name: Delete all other VS config
was this to deal with parent child complications during cleanup?

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +    - name: Delete all VS config
will not work with pagination

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviAbsent/local.yml
> +    - name: Delete all VS config
If you have a list of all the assets in avi_Config style then you can use the same dictionary to delete everything. check this out. 
https://gitlab.eng.vmware.com/rastogiga/vmexplore-2022-secops

2022-08-02 17:53 UTC, grastogi23 commented on ansible/aviConfigure/vmw/pbVsVmw.yml
> +        avi_credentials: "{{ avi_credentials | default(omit) }}"
let us check if these work outside of the admin tenant.

2022-08-03 15:28 UTC, itlinux commented on ansible/aviAbsent/local.yml
> +    - name: Delete all other VS config
Yes this is the reason to clean up.

2022-08-03 15:29 UTC, itlinux commented on ansible/aviAbsent/local.yml
> +    - name: Delete child VS config
we do not really need any filters, in case we can check for other options. But it works just fine now.

2022-08-03 15:29 UTC, itlinux commented on ansible/aviAbsent/local.yml
> +    - name: get VS
this is a demo and we will not have 100 vs. Just 6.

2022-08-03 15:30 UTC, itlinux commented on ansible/aviAbsent/local.yml
> +      ignore_errors: yes
This is needed in case the GSLB is not the leader in the cluster.

2022-08-03 19:28 UTC, grastogi23 approved these changes

2022-08-03 19:29 UTC, merged